/**
 * Matlens Figma Plugin ビルドスクリプト
 *
 * `design-tokens/figma-plugin/code.ts` を esbuild でバンドルし、
 * Figma プラグインランタイム用の単一ファイル `code.js` を生成する。
 *
 * 実行:
 *   node design-tokens/scripts/build-plugin.ts
 *
 * Node 22+ / 25 のネイティブ TypeScript 型ストリッピングを利用しているため
 * 追加の transpile ツールは不要。プロジェクトの devDep である esbuild のみ使う。
 */

import { build } from 'esbuild';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';

const scriptDir = dirname(fileURLToPath(import.meta.url));
const pluginDir = resolve(scriptDir, '..', 'figma-plugin');

async function main(): Promise<void> {
  const result = await build({
    entryPoints: [resolve(pluginDir, 'code.ts')],
    outfile: resolve(pluginDir, 'code.js'),
    bundle: true,
    // Figma プラグインランタイムは ES2020 相当をサポート
    target: 'es2020',
    format: 'iife',
    platform: 'browser',
    // Figma は `figma` をグローバルで提供するのでバンドルから除外不要
    // (code.ts では declare const figma: any で参照している)
    minify: false,
    sourcemap: false,
    // 末尾に改行を付けて見やすく
    banner: { js: '// Auto-generated by design-tokens/scripts/build-plugin.ts\n// DO NOT EDIT — edit code.ts instead and re-run `npm run build:figma-plugin`\n' },
    logLevel: 'info',
  });

  if (result.errors.length > 0) {
    console.error('Build failed:', result.errors);
    process.exit(1);
  }

  console.log(`✅ Built ${resolve(pluginDir, 'code.js')}`);
}

main().catch(err => {
  console.error(err);
  process.exit(1);
});
