// Auto-generated by design-tokens/scripts/build-plugin.ts
// DO NOT EDIT — edit code.ts instead and re-run `npm run build:figma-plugin`

"use strict";
(() => {
  // design-tokens/src/types.ts
  var THEME_IDS = ["light", "dark", "eng", "cae"];

  // design-tokens/src/colorTokens.ts
  var COLOR_TOKENS = [
    // ───── Role colors ──────────────────────────────────────────
    {
      name: "accent",
      description: "\u30D7\u30E9\u30A4\u30DE\u30EA\u30A2\u30AF\u30BB\u30F3\u30C8",
      values: { light: "#004590", dark: "#5a9ae0", eng: "#00c896", cae: "#e89020" }
    },
    {
      name: "accent-hover",
      description: "\u30DB\u30D0\u30FC\u6642\u30A2\u30AF\u30BB\u30F3\u30C8",
      values: { light: "#003070", dark: "#78b0ec", eng: "#00e0aa", cae: "#f0a838" }
    },
    {
      name: "accent-dim",
      description: "\u30A2\u30AF\u30BB\u30F3\u30C8\u8584\u8272\u80CC\u666F",
      values: { light: "#dce8f7", dark: "#0e1e36", eng: "#0d2920", cae: "#201608" }
    },
    {
      name: "accent-mid",
      description: "\u30A2\u30AF\u30BB\u30F3\u30C8\u4E2D\u9593\u8272",
      values: { light: "#1a6bc0", dark: "#5a9ae0", eng: "#00c896", cae: "#e89020" }
    },
    // ───── AI ───────────────────────────────────────────────────
    {
      name: "ai-col",
      description: "AI \u6A5F\u80FD\u30AB\u30E9\u30FC",
      values: { light: "#3b35a0", dark: "#9a92f0", eng: "#60a8e8", cae: "#60c8f0" }
    },
    {
      name: "ai-dim",
      description: "AI \u8584\u8272\u80CC\u666F",
      values: { light: "#ebebfa", dark: "#1a1830", eng: "#0e1a28", cae: "#0c1820" }
    },
    {
      name: "ai-mid",
      description: "AI \u4E2D\u9593\u8272",
      values: { light: "#5c56cc", dark: "#9a92f0", eng: "#60a8e8", cae: "#60c8f0" }
    },
    // ───── Vector search ────────────────────────────────────────
    {
      name: "vec",
      description: "\u30D9\u30AF\u30C8\u30EB\u691C\u7D22\u30AB\u30E9\u30FC",
      values: { light: "#0a6657", dark: "#38d0b0", eng: "#a0e060", cae: "#30d8c0" }
    },
    {
      name: "vec-dim",
      description: "\u30D9\u30AF\u30C8\u30EB\u8584\u8272\u80CC\u666F",
      values: { light: "#d8f0eb", dark: "#082420", eng: "#101c08", cae: "#081c18" }
    },
    {
      name: "vec-mid",
      description: "\u30D9\u30AF\u30C8\u30EB\u4E2D\u9593\u8272",
      values: { light: "#0f8f78", dark: "#38d0b0", eng: "#a0e060", cae: "#30d8c0" }
    },
    // ───── Status ───────────────────────────────────────────────
    {
      name: "ok",
      description: "\u6210\u529F\u30FB\u5B8C\u4E86",
      values: { light: "#1e6b0f", dark: "#6cc850", eng: "#5cc840", cae: "#60c840" }
    },
    {
      name: "ok-dim",
      description: "\u6210\u529F\u8584\u8272\u80CC\u666F",
      values: { light: "#e4f3de", dark: "#0e1f08", eng: "#0e1e08", cae: "#0e1e08" }
    },
    {
      name: "warn",
      description: "\u8B66\u544A",
      values: { light: "#7a4b00", dark: "#f0b040", eng: "#e8b040", cae: "#f0a030" }
    },
    {
      name: "warn-dim",
      description: "\u8B66\u544A\u8584\u8272\u80CC\u666F",
      values: { light: "#fdf0d8", dark: "#201600", eng: "#1a1400", cae: "#180c00" }
    },
    {
      name: "err",
      description: "\u30A8\u30E9\u30FC\u30FB\u5371\u967A",
      values: { light: "#8b1a1a", dark: "#f06060", eng: "#f05050", cae: "#f05840" }
    },
    {
      name: "err-dim",
      description: "\u30A8\u30E9\u30FC\u8584\u8272\u80CC\u666F",
      values: { light: "#fdeaea", dark: "#200808", eng: "#1e0808", cae: "#1c0808" }
    },
    // ───── Background ───────────────────────────────────────────
    {
      name: "bg/base",
      description: "\u30DA\u30FC\u30B8\u80CC\u666F",
      values: { light: "#eef0f3", dark: "#10141c", eng: "#1a1f26", cae: "#0e1014" }
    },
    {
      name: "bg/surface",
      description: "\u30AB\u30FC\u30C9\u30FB\u30D1\u30CD\u30EB\u80CC\u666F",
      values: { light: "#ffffff", dark: "#181d28", eng: "#222830", cae: "#14181e" }
    },
    {
      name: "bg/raised",
      description: "\u6D6E\u304D\u4E0A\u304C\u308A\u8981\u7D20",
      values: { light: "#f5f6f8", dark: "#1f2535", eng: "#2a3040", cae: "#1c2028" }
    },
    {
      name: "bg/sunken",
      description: "\u6C88\u307F\u8FBC\u307F\u8981\u7D20",
      values: { light: "#e4e6ea", dark: "#0c1018", eng: "#141820", cae: "#0a0c10" }
    },
    {
      name: "bg/hover",
      description: "\u30DB\u30D0\u30FC\u72B6\u614B",
      values: { light: "#e8eef7", dark: "#232c3e", eng: "#2e3848", cae: "#1e2430" }
    },
    {
      name: "bg/active",
      description: "\u30A2\u30AF\u30C6\u30A3\u30D6\u72B6\u614B",
      values: { light: "#d4e2f4", dark: "#1a2d4a", eng: "#1a2e48", cae: "#142030" }
    },
    // ───── Text ─────────────────────────────────────────────────
    {
      name: "text/hi",
      description: "\u9AD8\u30B3\u30F3\u30C8\u30E9\u30B9\u30C8 (\u898B\u51FA\u3057)",
      values: { light: "#0d1520", dark: "#e8f0ff", eng: "#d8eaf8", cae: "#f0ece4" }
    },
    {
      name: "text/md",
      description: "\u4E2D\u30B3\u30F3\u30C8\u30E9\u30B9\u30C8 (\u672C\u6587)",
      values: { light: "#3a4554", dark: "#a8bcd8", eng: "#92b0cc", cae: "#b8a898" }
    },
    {
      name: "text/lo",
      description: "\u4F4E\u30B3\u30F3\u30C8\u30E9\u30B9\u30C8 (\u88DC\u52A9)",
      values: { light: "#6b7a8d", dark: "#6e84a0", eng: "#5e7890", cae: "#6e6058" }
    },
    // ───── Border ───────────────────────────────────────────────
    {
      name: "border/focus",
      description: "\u30D5\u30A9\u30FC\u30AB\u30B9\u30EA\u30F3\u30B0",
      values: { light: "#0050AA", dark: "#5a9eff", eng: "#00c896", cae: "#e89020" }
    },
    // ───── UI chrome ────────────────────────────────────────────
    {
      name: "topbar-bg",
      description: "\u30C8\u30C3\u30D7\u30D0\u30FC\u80CC\u666F",
      values: { light: "#1e3050", dark: "#0c1018", eng: "#141820", cae: "#0a0c10" }
    },
    {
      name: "sidebar-bg",
      description: "\u30B5\u30A4\u30C9\u30D0\u30FC\u80CC\u666F",
      values: { light: "#ffffff", dark: "#181d28", eng: "#1a1f26", cae: "#0e1014" }
    },
    {
      name: "tag-surface",
      description: "\u30BF\u30B0\u80CC\u666F",
      values: { light: "#e8ebef", dark: "#1f2535", eng: "#1a2028", cae: "#181c20" }
    }
  ];

  // design-tokens/src/sizeTokens.ts
  var SPACING_TOKENS = [
    { name: "spacing/0.5", value: 2, description: "\u6700\u5C0F\u9593\u9694 (\u30A2\u30A4\u30B3\u30F3\u5468\u8FBA)" },
    { name: "spacing/1", value: 4, description: "\u6975\u5C0F\u9593\u9694" },
    { name: "spacing/1.5", value: 6, description: "\u5C0F\u9593\u9694" },
    { name: "spacing/2", value: 8, description: "\u30B3\u30F3\u30D1\u30AF\u30C8" },
    { name: "spacing/2.5", value: 10 },
    { name: "spacing/3", value: 12 },
    { name: "spacing/4", value: 16, description: "\u6A19\u6E96 (1rem)" },
    { name: "spacing/5", value: 20 },
    { name: "spacing/6", value: 24, description: "\u30BB\u30AF\u30B7\u30E7\u30F3\u9593" },
    { name: "spacing/8", value: 32 },
    { name: "spacing/10", value: 40 },
    { name: "spacing/12", value: 48, description: "\u5927\u30BB\u30AF\u30B7\u30E7\u30F3\u9593" }
  ];
  var RADIUS_TOKENS = [
    {
      name: "radius/sm",
      description: "\u5C0F\u8981\u7D20 (\u30DC\u30BF\u30F3\u7B49)",
      values: { light: 4, dark: 4, eng: 3, cae: 2 }
    },
    {
      name: "radius/md",
      description: "\u30AB\u30FC\u30C9\u7B49",
      values: { light: 6, dark: 6, eng: 5, cae: 4 }
    },
    {
      name: "radius/lg",
      description: "\u30E2\u30FC\u30C0\u30EB\u7B49",
      values: { light: 10, dark: 10, eng: 8, cae: 6 }
    },
    {
      name: "radius/xl",
      description: "\u5927\u30D1\u30CD\u30EB",
      values: { light: 14, dark: 14, eng: 12, cae: 10 }
    }
  ];

  // design-tokens/src/textStyles.ts
  var TEXT_STYLES = [
    {
      name: "Matlens/Heading/H1",
      description: "\u30C0\u30C3\u30B7\u30E5\u30DC\u30FC\u30C9\u5927\u898B\u51FA\u3057",
      fontSize: 19,
      fontWeight: "Bold",
      lineHeightRatio: 1.4
    },
    {
      name: "Matlens/Heading/H2",
      description: "\u30DA\u30FC\u30B8\u898B\u51FA\u3057",
      fontSize: 17,
      fontWeight: "Bold",
      lineHeightRatio: 1.4
    },
    {
      name: "Matlens/Heading/H3",
      description: "\u30BB\u30AF\u30B7\u30E7\u30F3\u898B\u51FA\u3057",
      fontSize: 16,
      fontWeight: "Bold",
      lineHeightRatio: 1.4
    },
    {
      name: "Matlens/Heading/Subhead",
      description: "\u30E2\u30FC\u30C0\u30EB\u898B\u51FA\u3057",
      fontSize: 15,
      fontWeight: "Semi Bold",
      lineHeightRatio: 1.4
    },
    {
      name: "Matlens/Body/Base",
      description: "\u30D9\u30FC\u30B9\u30D5\u30A9\u30F3\u30C8 (1rem)",
      fontSize: 14,
      fontWeight: "Regular",
      lineHeightRatio: 1.6
    },
    {
      name: "Matlens/Body/Default",
      description: "\u672C\u6587\u30FB\u5165\u529B\u30D5\u30A3\u30FC\u30EB\u30C9",
      fontSize: 13,
      fontWeight: "Regular",
      lineHeightRatio: 1.6
    },
    {
      name: "Matlens/Label/Nav",
      description: "\u30CA\u30D3\u30FB\u30D5\u30A9\u30FC\u30E0\u30E9\u30D9\u30EB",
      fontSize: 12,
      fontWeight: "Medium",
      lineHeightRatio: 1.4
    },
    {
      name: "Matlens/Label/Badge",
      description: "\u30D0\u30C3\u30B8\u30FB\u88DC\u52A9\u30E9\u30D9\u30EB",
      fontSize: 12,
      fontWeight: "Semi Bold",
      lineHeightRatio: 1.2
    },
    {
      name: "Matlens/Code/Mono",
      description: "\u30B3\u30FC\u30C9\u30FB\u6570\u5024 (\u7B49\u5E45\u60F3\u5B9A)",
      fontSize: 13,
      fontWeight: "Regular",
      lineHeightRatio: 1.5
    }
  ];

  // design-tokens/src/shadowStyles.ts
  var SHADOW_TOKENS = [
    {
      name: "Matlens/Shadow/XS",
      description: "\u30DC\u30BF\u30F3\u30FB\u30D0\u30C3\u30B8 (\u5FAE\u5F31\u306A\u6D6E\u304D)",
      offsetY: 1,
      blur: 2,
      alpha: 0.06
    },
    {
      name: "Matlens/Shadow/SM",
      description: "\u30AB\u30FC\u30C9\u30FB\u30C9\u30ED\u30C3\u30D7\u30C0\u30A6\u30F3",
      offsetY: 2,
      blur: 6,
      alpha: 0.08
    },
    {
      name: "Matlens/Shadow/MD",
      description: "\u30E2\u30FC\u30C0\u30EB\u30FB\u30DD\u30C3\u30D7\u30AA\u30FC\u30D0\u30FC",
      offsetY: 4,
      blur: 16,
      alpha: 0.1
    },
    {
      name: "Matlens/Shadow/LG",
      description: "\u30D5\u30ED\u30FC\u30C6\u30A3\u30F3\u30B0\u30D1\u30CD\u30EB",
      offsetY: 8,
      blur: 36,
      alpha: 0.13
    }
  ];

  // design-tokens/figma-plugin/code.ts
  function parseColor(input) {
    const trimmed = input.trim();
    if (trimmed.startsWith("rgba")) {
      const match = trimmed.match(/rgba?\(([^)]+)\)/i);
      if (!match) throw new Error(`Invalid rgba color: ${input}`);
      const parts = match[1].split(",").map((s) => parseFloat(s.trim()));
      const [r, g, b, a = 1] = parts;
      return { r: r / 255, g: g / 255, b: b / 255, a };
    }
    const hex = trimmed.replace("#", "");
    if (hex.length !== 6) throw new Error(`Invalid hex color: ${input}`);
    return {
      r: parseInt(hex.substring(0, 2), 16) / 255,
      g: parseInt(hex.substring(2, 4), 16) / 255,
      b: parseInt(hex.substring(4, 6), 16) / 255,
      a: 1
    };
  }
  function createThemedCollection(name) {
    const collection = figma.variables.createVariableCollection(name);
    collection.renameMode(collection.modes[0].modeId, "light");
    const modeIds = {
      light: collection.modes[0].modeId,
      dark: collection.addMode("dark"),
      eng: collection.addMode("eng"),
      cae: collection.addMode("cae")
    };
    return { collection, modeIds };
  }
  function registerColorTokens() {
    const { collection, modeIds } = createThemedCollection("Color Tokens");
    for (const token of COLOR_TOKENS) {
      const variable = figma.variables.createVariable(token.name, collection.id, "COLOR");
      if (token.description) variable.description = token.description;
      for (const themeId of THEME_IDS) {
        variable.setValueForMode(modeIds[themeId], parseColor(token.values[themeId]));
      }
    }
  }
  function registerSizeTokens() {
    const { collection, modeIds } = createThemedCollection("Size Tokens");
    for (const token of SPACING_TOKENS) {
      const variable = figma.variables.createVariable(token.name, collection.id, "FLOAT");
      if (token.description) variable.description = token.description;
      for (const themeId of THEME_IDS) {
        variable.setValueForMode(modeIds[themeId], token.value);
      }
    }
    for (const token of RADIUS_TOKENS) {
      const variable = figma.variables.createVariable(token.name, collection.id, "FLOAT");
      if (token.description) variable.description = token.description;
      for (const themeId of THEME_IDS) {
        variable.setValueForMode(modeIds[themeId], token.values[themeId]);
      }
    }
  }
  var REQUIRED_FONT_WEIGHTS = [
    "Regular",
    "Medium",
    "Semi Bold",
    "Bold"
  ];
  async function registerTextStyles() {
    await Promise.all(
      REQUIRED_FONT_WEIGHTS.map(
        (style) => figma.loadFontAsync({ family: "Inter", style })
      )
    );
    for (const style of TEXT_STYLES) {
      const textStyle = figma.createTextStyle();
      textStyle.name = style.name;
      textStyle.description = style.description;
      textStyle.fontSize = style.fontSize;
      textStyle.fontName = { family: "Inter", style: style.fontWeight };
      textStyle.lineHeight = {
        value: style.fontSize * style.lineHeightRatio,
        unit: "PIXELS"
      };
    }
  }
  function registerShadowStyles() {
    for (const shadow of SHADOW_TOKENS) {
      const effectStyle = figma.createEffectStyle();
      effectStyle.name = shadow.name;
      effectStyle.description = shadow.description;
      effectStyle.effects = [
        {
          type: "DROP_SHADOW",
          // light テーマのシャドウ色 (rgb(0, 20, 60) 系) をベースに、
          // alpha だけをトークンから取る
          color: { r: 0, g: 0.08, b: 0.24, a: shadow.alpha },
          offset: { x: 0, y: shadow.offsetY },
          radius: shadow.blur,
          spread: 0,
          visible: true,
          blendMode: "NORMAL"
        }
      ];
    }
  }
  function countByCategory(tokens) {
    return tokens.length;
  }
  async function main() {
    try {
      registerColorTokens();
      registerSizeTokens();
      registerShadowStyles();
      await registerTextStyles();
      const summary = [
        `\u30AB\u30E9\u30FC ${countByCategory(COLOR_TOKENS)}\u5909\u6570 \xD7 4\u30E2\u30FC\u30C9`,
        `\u30B5\u30A4\u30BA ${SPACING_TOKENS.length + RADIUS_TOKENS.length}\u5909\u6570`,
        `\u30C6\u30AD\u30B9\u30C8 ${TEXT_STYLES.length}\u30B9\u30BF\u30A4\u30EB`,
        `\u30B7\u30E3\u30C9\u30A6 ${SHADOW_TOKENS.length}\u30B9\u30BF\u30A4\u30EB`
      ].join(", ");
      figma.notify(`\u2705 Matlens Design Tokens \u767B\u9332\u5B8C\u4E86: ${summary}`);
    } catch (error) {
      const message = error instanceof Error ? error.message : String(error);
      figma.notify(`\u274C \u767B\u9332\u5931\u6557: ${message}`, { error: true, timeout: 8e3 });
      console.error(error);
    } finally {
      figma.closePlugin();
    }
  }
  void main();
})();
